### ISSUE TITLE
Tangram Meta-issue

### ISSUE THREAD

**Issue by donflopez** [CartoDB/tangram-cartocss#11]
We have several problems with the Tangram integration, I've put here the most important ones.

- [x] Alpha channel with blend #12 
- [x] Polygons draws are buggy #13
- [x] Lines looks like triangles [#457](https://github.com/tangrams/tangram/issues/457)
- [x] Use of `blend:multiply` turns everything black
- [x] Use of opacity make the other layers disappear #14
- [x] Points can't have `marker-line` from the scratch #15
- [x] Static line width #NaN (fixed)
- [ ] Collision aggregations tangram side #NaN
- [ ] Rendering time #NaN
- [ ] MVT serving time #NaN

/cc @rochoa && @javisantana

**Comment by rochoa** [comment]
I don't know what the "collision" task refers to. The other two pending tasks, regarding metrics, don't seem to belong here.
